Repository google/snippet-uiautomator, pull requests merged in 2023-12, with the labels that each got.

#28 Implement UiAutomation.clearCache API for SDK 34 or higher device
  snippet_uiautomator/android/app/src/main/AndroidManifest.xml
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/ConfiguratorSnippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiAutomationSnippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiAutomator.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiDeviceSnippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiWatcherSnippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/selector/PositionSelector.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/selector/Selector.java
  snippet_uiautomator/android/app/uiautomator.apk
  snippet_uiautomator/uidevice.py
Labels: enhancement

#29 Fix sibling find the grandchildren object
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/selector/BySelectorMap.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/selector/Selector.java
  snippet_uiautomator/android/app/uiautomator.apk
Labels: bug

#30 Handle NullPointerException throw from Until#scrollUntilFinished
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiObject2Snippet.java
  snippet_uiautomator/android/app/uiautomator.apk
Labels: bug

#32 Enable UiWatcher to monitor the condition without subsequent action.
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiWatcherSnippet.java
  snippet_uiautomator/android/app/uiautomator.apk
  snippet_uiautomator/uiwatcher.py
Labels: enhancement

#33 Set default value for uiautomator configs and send warning message for deprecation notice
  README.md
  docs/uidevice.md
  snippet_uiautomator/uiautomator.py
Labels: refactor

#34 Support KeyEvent in UiAutomator Python Lib
  docs/uidevice.md
  docs/uiwatcher.md
  snippet_uiautomator/constants.py
  snippet_uiautomator/uiautomator.py
Labels: enhancement

#35 Update androidx.test.uiautomator to 2.3.0-beta01
  snippet_uiautomator/android/app/build.gradle
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiObject2Snippet.java
  snippet_uiautomator/android/app/uiautomator.apk
Labels: refactor

#37 Update the visibility of uiDevice in UiDeviceSnippet
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiDeviceSnippet.java
Labels: testing

#38 Handle null value returned from QueryController.getCurrentPackageName
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/Info.java
  snippet_uiautomator/android/app/uiautomator.apk
Labels: bug
