Repository google/snippet-uiautomator, pull requests merged in 2023-09, with the labels that each got.

#5 Fix incorrect UiObject2 being found when using waitForExists and waitUntilGone on 2 or more layers of BySelector
  CHANGELOG.md
  snippet_uiautomator/android/app/build.gradle
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiObject2Snippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/Utils.java
  snippet_uiautomator/android/app/uiautomator.apk
Labels: bug

#6 Fix Selector being overwritten when creating an instance of child UiObject2
  CHANGELOG.md
  snippet_uiautomator/byselector.py
  snippet_uiautomator/uiobject2.py
Labels: bug

#9 Fix pylint issue: unused Union imported from typing (unused-import).
  snippet_uiautomator/uiwatcher.py
Labels: refactor

#13 Fix pylint issue: missing function or method docstring.
  snippet_uiautomator/uiautomator.py
Labels: refactor

#12 Fix pylint issue: unnecessarily calls dunder method, invoke directly
  snippet_uiautomator/uiobject2.py
Labels: refactor

#15 Fix pylint issue: use open without explicitly specifying an encoding.
  snippet_uiautomator/uidevice.py
Labels: refactor

#14 Fix pylint issue: merge isinstance calls (consider-merging-isinstance).
  snippet_uiautomator/uidevice.py
Labels: refactor

#11 Fix pylint issue: __init__ method from base class is not called
  snippet_uiautomator/uiautomator.py
Labels: refactor

#16 Fix pylint issue: inconsistent return statement.
  snippet_uiautomator/uidevice.py
Labels: refactor

#7 Add continuous integration support for google/snippet-uiautomator
  .github/workflows/ci.yml
  README.md
  pylintrc
Labels: testing

#17 Fix incorrect selector layer when using a serial of sub selectors
  CHANGELOG.md
  setup.py
  snippet_uiautomator/byselector.py
Labels: bug

#18 Enable Github Actions to build the apk
  .github/workflows/app.yml
Labels: testing

#19 Add latest release version and testing result for apk and python build status
  .DS_Store
  .github/.DS_Store
  .github/workflows/apk.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  setup.py
Labels: documentation

#20 Fix typo on the badge link of APK build status
  README.md
Labels: documentation

#22 Add first test and enable pytest+coverage in CI
  .DS_Store
  .coveragerc
  .github/workflows/ci.yml
  .gitignore
  README.md
  pyproject.toml
  tests/utils_test.py
Labels: testing

#23 Fix the import order to follow Google Python Style.
  tests/utils_test.py
Labels: refactor

#24 Change the Pyformat and add it to git pre-commit hook.
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  docs/configurator.md
  docs/selector.md
  docs/uidevice.md
  pylintrc
  pyproject.toml
  snippet_uiautomator/__init__.py
  snippet_uiautomator/android/app/.gitignore
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/ConfiguratorSnippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/Converter.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/Info.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiObject2Snippet.java
  snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/selector/BySelectorMap.java
  snippet_uiautomator/android/gradle.properties
  snippet_uiautomator/byselector.py
  snippet_uiautomator/configurator.py
  snippet_uiautomator/constants.py
  snippet_uiautomator/errors.py
  snippet_uiautomator/uiautomator.py
  snippet_uiautomator/uiobject2.py
  snippet_uiautomator/uiwatcher.py
  snippet_uiautomator/utils.py
  tests/utils_test.py
Labels: refactor

#21 Raise an error when uiautomation service has already registered
  CHANGELOG.md
  snippet_uiautomator/errors.py
  snippet_uiautomator/uiautomator.py
  snippet_uiautomator/utils.py
  tests/utils_test.py
Labels: enhancement

#25 Parse byte string before decoding to string
  snippet_uiautomator/utils.py
Labels: bug
